#!/usr/bin/env python3
"""
Generate the .env file for Flownative Beach from Snipe-IT's .env.example.

The .env is never edited by hand. It is generated from the .env.example that
ships with the current Snipe-IT version, with the Flownative specific values
below applied on top. Run this after upgrading to a new upstream version:

    python3 beach-build-env.py

Then review the diff. Variables that upstream added appear with their default,
variables that upstream removed are gone, and a renamed variable shows up as
one addition plus one removal — which is exactly what needs a decision.

Values in ${...} form are references to Beach instance variables and are
resolved at runtime. Literal credentials must never be stored in this file.
"""

import re
import sys
from pathlib import Path

# Values that deviate from the upstream defaults. Everything not listed here is
# taken from .env.example unchanged.
OVERRIDES = {
    # APP_TIMEZONE and APP_LOCALE are deliberately literal. Laravel validates
    # both while bootstrapping, and the Beach instance variables do not exist
    # inside the build container — unresolved placeholders would break the
    # "artisan package:discover" call during composer install.
    'APP_TIMEZONE': "'UTC'",
    'APP_LOCALE': "'de-if'",

    'APP_KEY': '${APP_KEY}',
    'APP_URL': '${APP_URL}',
    'APP_TRUSTED_PROXIES': '${APP_TRUSTED_PROXIES}',

    # Uploads go to the S3 bucket, not into the container: everything below
    # storage/ is reset whenever the instance restarts.
    'PRIVATE_FILESYSTEM_DISK': 's3_private',
    'PUBLIC_FILESYSTEM_DISK': 's3_public',

    'DB_HOST': '${BEACH_DATABASE_HOST}',
    'DB_PORT': '${BEACH_DATABASE_PORT}',
    'DB_DATABASE': '${BEACH_DATABASE_NAME}',
    'DB_USERNAME': '${BEACH_DATABASE_USERNAME}',
    'DB_PASSWORD': '${BEACH_DATABASE_PASSWORD}',

    'MAIL_HOST': 'smtp.postmarkapp.com',
    'MAIL_USERNAME': '${MAIL_USERNAME}',
    'MAIL_PASSWORD': '${MAIL_PASSWORD}',
    'MAIL_FROM_ADDR': '${MAIL_FROM_ADDR}',
    'MAIL_FROM_NAME': "'Snipe-IT'",
    'MAIL_REPLYTO_ADDR': 'noreply@flownative.com',
    'MAIL_REPLYTO_NAME': "'Snipe-IT'",
    'MAIL_AUTO_EMBED_METHOD': "'attachment'",
    'MAIL_TLS_VERIFY_PEER': 'true',

    'SESSION_DRIVER': 'redis',
    'COOKIE_DOMAIN': '${COOKIE_DOMAIN}',
    'SECURE_COOKIES': '${SECURE_COOKIES}',
    'BS_TABLE_STORAGE': 'cookieStorage',
    'ENABLE_CSP': 'false',

    'REDIS_HOST': '${BEACH_REDIS_HOST}',
    'REDIS_PASSWORD': '${BEACH_REDIS_PASSWORD}',
    'REDIS_PORT': '6379',

    'PUBLIC_AWS_ACCESS_KEY_ID': '${PUBLIC_AWS_ACCESS_KEY_ID}',
    'PUBLIC_AWS_SECRET_ACCESS_KEY': '${PUBLIC_AWS_SECRET_ACCESS_KEY}',
    'PUBLIC_AWS_DEFAULT_REGION': '${PUBLIC_AWS_DEFAULT_REGION}',
    'PUBLIC_AWS_BUCKET': '${PUBLIC_AWS_BUCKET}',
    'PUBLIC_AWS_URL': '${PUBLIC_AWS_URL}',
    'PUBLIC_AWS_BUCKET_ROOT': '${PUBLIC_AWS_BUCKET_ROOT}',

    'PRIVATE_AWS_ACCESS_KEY_ID': '${PRIVATE_AWS_ACCESS_KEY_ID}',
    'PRIVATE_AWS_SECRET_ACCESS_KEY': '${PRIVATE_AWS_SECRET_ACCESS_KEY}',
    'PRIVATE_AWS_DEFAULT_REGION': '${PRIVATE_AWS_DEFAULT_REGION}',
    'PRIVATE_AWS_BUCKET': '${PRIVATE_AWS_BUCKET}',
    'PRIVATE_AWS_URL': '${PRIVATE_AWS_URL}',
    'PRIVATE_AWS_BUCKET_ROOT': '${PRIVATE_AWS_BUCKET_ROOT}',

    'AWS_ACCESS_KEY_ID': '${AWS_ACCESS_KEY_ID}',
    'AWS_SECRET_ACCESS_KEY': '${AWS_SECRET_ACCESS_KEY}',
    'AWS_DEFAULT_REGION': '${AWS_DEFAULT_REGION}',
}

HEADER = """# --------------------------------------------
# Flownative Beach
#
# Generated by beach-build-env.py from .env.example - do not edit by hand.
# Instance specific values are references to Beach instance variables in the
# form ${VARIABLE} and are resolved at runtime. Literal credentials must never
# be stored in this file.
#
# After upgrading to a new Snipe-IT version, run the script again and review
# the resulting diff.
# --------------------------------------------

"""

ASSIGNMENT = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*)=(.*)$')

# Names that look like a secret but hold plain numbers (timeouts, key lengths).
NOT_SECRETS = {
    'RESET_PASSWORD_LINK_EXPIRES', 'PASSWORD_CONFIRM_TIMEOUT',
    'PASSWORD_RESET_MAX_ATTEMPTS_PER_MIN', 'INVITE_PASSWORD_LINK_EXPIRES',
    'SAML_KEY_SIZE', 'API_TOKEN_EXPIRATION_YEARS',
}


def parse(path):
    values = {}
    for line in path.read_text(encoding='utf-8').splitlines():
        match = ASSIGNMENT.match(line)
        if match:
            values[match.group(1)] = match.group(2)
    return values


def main():
    root = Path(__file__).resolve().parent
    example, target = root / '.env.example', root / '.env'

    if not example.is_file():
        sys.exit(f'error: {example} not found')

    previous = parse(target) if target.is_file() else {}

    lines, applied = [], set()
    for line in example.read_text(encoding='utf-8').splitlines(keepends=True):
        match = ASSIGNMENT.match(line.rstrip('\n'))
        if match and match.group(1) in OVERRIDES:
            key = match.group(1)
            applied.add(key)
            lines.append(f'{key}={OVERRIDES[key]}\n')
        else:
            lines.append(line)

    # An override without a counterpart means upstream renamed or dropped the
    # variable. That needs a decision, so refuse to write a half-correct file.
    orphaned = sorted(set(OVERRIDES) - applied)
    if orphaned:
        sys.exit(
            'error: no counterpart in .env.example for: ' + ', '.join(orphaned) +
            '\nUpstream probably renamed or removed these. Adjust OVERRIDES.'
        )

    target.write_text(HEADER + ''.join(lines), encoding='utf-8')
    current = parse(target)

    print(f'Wrote {target.name}: {len(current)} variables, {len(applied)} overrides applied.')

    if previous:
        for key in sorted(set(current) - set(previous)):
            print(f'  added:   {key}={current[key]}')
        for key in sorted(set(previous) - set(current)):
            print(f'  removed: {key}')

    leaked = [
        key for key, value in current.items()
        if re.search(r'KEY|PASSWORD|SECRET|TOKEN', key)
        and key not in NOT_SECRETS
        and value and not value.startswith('${')
        and value not in ('null', 'ChangeMe', 'false', 'true')
    ]
    if leaked:
        sys.exit('error: literal value in a secret variable: ' + ', '.join(leaked))


if __name__ == '__main__':
    main()
